// Short descriptions are model inputs, separate from the user-facing usage guides.
export const semanticDescriptions: Record<string, string> = {
    menu: 'Mostrar menu e lista de comandos disponíveis.',
    d: 'Baixar vídeo ou mídia de um link.',
    play: 'Buscar e tocar uma música pelo nome.',
    mp3: 'Extrair o áudio de um vídeo, converter para mp3.',
    img: 'Pesquisar imagens sobre um assunto.',
    s: 'Criar figurinha ou sticker de foto, vídeo ou texto.',
    simg: 'Converter uma figurinha em imagem.',
    revelar: 'Revelar mídia de visualização única.',
    save: 'Salvar um áudio com um nome na biblioteca.',
    audio: 'Reproduzir um áudio salvo pelo nome.',
    v: 'Criar vídeo com foto do membro e áudio salvo.',
    audios: 'Listar os áudios salvos disponíveis.',
    delete: 'Excluir um áudio salvo da biblioteca.',
    rename: 'Renomear um áudio salvo.',
    vtnc: 'Enviar desenho ASCII para um membro.',
    ask: 'Perguntar ao assistente como usar o bot.',
    config: 'Configurar o nível de ajuda nos erros.',
    silenciar: 'Silenciar ou desmutar um membro do grupo.',
    addlista: 'Colocar pessoa na lista negra, bloquear sua entrada no grupo.',
    rmlista: 'Remover membro da lista negra.',
    listanegra: 'Consultar a lista negra do grupo.',
    add: 'Adicionar uma pessoa ao grupo pelo telefone.',
    ban: 'Banir ou expulsar uma pessoa do grupo.',
    promover: 'Promover uma pessoa a administrador.',
    rebaixar: 'Remover a administração, retirar o cargo de administrador de um membro.',
    apg: 'Apagar a mensagem respondida.',
    admin: 'Mostrar o menu de administração do bot.',
    comandospv: 'Ativar ou desativar comandos em conversas privadas.',
    taxacomandos: 'Configurar limite de comandos por usuário.',
    listablock: 'Listar os usuários bloqueados pelo bot.',
    bloquear: 'Bloquear uma pessoa no bot.',
    desbloquear: 'Desbloquear uma pessoa no bot.',
    usuario: 'Consultar dados de outro usuário do bot.',
    ping: 'Medir tempo de resposta e desempenho do bot.',
}

export const semanticFamilyDescriptions: Record<string, string> = {
    utility: 'Mídia: músicas, vídeos, imagens, figurinhas e áudios.',
    group_information: 'Consultar a lista negra do grupo.',
    group_members: 'Moderação: banir, silenciar, promover e rebaixar membros.',
    group_media: 'Apagar mensagens do grupo.',
    group_settings: 'Configurações do grupo.',
    admin: 'Acesso, usuários e configurações do bot.'
}
